import { DOM_IDS } from '../constants';

export const STORAGE_KEYS = {
  SHOW_HIDDEN: DOM_IDS.STORAGE_KEY,
  SCROLL_GUARD: DOM_IDS.SCROLL_GUARD_STORAGE_KEY,
  DETECTION_MODE: DOM_IDS.DETECTION_MODE_STORAGE_KEY,
  RELOAD_NAVIGATION: DOM_IDS.RELOAD_ON_NAVIGATION_STORAGE_KEY,
  VIEWED_COLOR: DOM_IDS.VIEWED_HIGHLIGHT_COLOR_STORAGE_KEY,
  APPLIED_COLOR: DOM_IDS.APPLIED_HIGHLIGHT_COLOR_STORAGE_KEY,
  ACTIVE_COLOR: DOM_IDS.ACTIVE_HIGHLIGHT_COLOR_STORAGE_KEY,
  KEYWORD_COLOR: DOM_IDS.KEYWORD_HIGHLIGHT_COLOR_STORAGE_KEY,
  CUSTOM_KEYWORDS: DOM_IDS.CUSTOM_KEYWORDS_STORAGE_KEY,
  OPACITY: DOM_IDS.HIGHLIGHT_OPACITY_STORAGE_KEY,
} as const;

export const DEFAULTS: Record<string, string> = {
  [STORAGE_KEYS.VIEWED_COLOR]: '#2ecc71',
  [STORAGE_KEYS.APPLIED_COLOR]: '#f59e0b',
  [STORAGE_KEYS.ACTIVE_COLOR]: '#0a66c2',
  [STORAGE_KEYS.KEYWORD_COLOR]: '#9b59b6',
  [STORAGE_KEYS.OPACITY]: '0.10',
} as const;
