import type { IConfig, IDomIdentifiers } from '../types';

export const CONFIG: IConfig = Object.freeze({
  POLL_INTERVAL_MS: 2000,
  ROUTE_CHECK_INTERVAL_MS: 500,
  ROUTE_BURST_INTERVAL_MS: 250,
  ROUTE_BURST_MAX_TICKS: 12,
  LAZY_RENDER_TIMEOUT_MS: 8000,
  MUTATION_DEBOUNCE_MS: 80,
  UI_Z_INDEX: 99999,
  UI_EDGE_MARGIN: 8,
  ENABLE_HIGHLIGHT: true,
  HIGHLIGHT_COLOR: 'rgba(46, 204, 113, 0.95)',
  HIGHLIGHT_BORDER_RADIUS: '6px',
  SCROLL_GUARD_ENABLED_DEFAULT: true,
  SCROLL_GUARD_TRIGGER_DELTA_PX: 900,
  SCROLL_GUARD_TRIGGER_WINDOW_MS: 1200,
  SCROLL_GUARD_COOLDOWN_MIN_MS: 5000,
  SCROLL_GUARD_COOLDOWN_MAX_MS: 15000,
  SCROLL_GUARD_ALLOWED_STEP_PX: 110,
  SCROLL_GUARD_ALLOWED_STEP_MIN_INTERVAL_MS: 120,
  SCROLL_GUARD_MIN_VIEWED_DENSITY: 0.55,
  SCROLL_GUARD_DENSITY_WINDOW_MS: 6000,
});

export const DOM_IDS: IDomIdentifiers = Object.freeze({
  STORAGE_KEY: 'lhvj-show-hidden',
  SCROLL_GUARD_STORAGE_KEY: 'lhvj-scroll-guard-enabled',
  DETECTION_MODE_STORAGE_KEY: 'lhvj-detection-mode',
  UI_POSITION_KEY: 'lhvj-ui-position',
  HIDDEN_CLASS: 'lhvj-hidden-by-script',
  UI_ID: 'lhvj-toggle-root',
  VIEWED_HIGHLIGHT_CLASS: 'lhvj-viewed-highlight',
});
