import type { IConfig, IDomIdentifiers } from '../types'

export const CONFIG: IConfig = Object.freeze({
  POLL_INTERVAL_MS: 2000,
  ROUTE_CHECK_INTERVAL_MS: 500,
  ROUTE_BURST_INTERVAL_MS: 250,
  ROUTE_BURST_MAX_TICKS: 12,
  LAZY_RENDER_TIMEOUT_MS: 8000,
  MUTATION_DEBOUNCE_MS: 80,
  UI_Z_INDEX: 99999,
  UI_EDGE_MARGIN: 8,
  ENABLE_HIGHLIGHT: true,
  VIEWED_HIGHLIGHT_COLOR: '#2ecc71',
  APPLIED_HIGHLIGHT_COLOR: '#f59e0b',
  ACTIVE_HIGHLIGHT_COLOR: '#0a66c2',
  KEYWORD_HIGHLIGHT_COLOR: '#9b59b6',
  HIGHLIGHT_OPACITY: 0.1,
  HIGHLIGHT_OPACITY_MIN: 0,
  HIGHLIGHT_OPACITY_MAX: 1,
  HIGHLIGHT_OPACITY_STEP: 0.01,
  HIGHLIGHT_BORDER_RADIUS: '6px',
  SCROLL_GUARD_ENABLED_DEFAULT: true,
  SCROLL_GUARD_TRIGGER_DELTA_PX: 900,
  SCROLL_GUARD_TRIGGER_WINDOW_MS: 1200,
  SCROLL_GUARD_COOLDOWN_MIN_MS: 5000,
  SCROLL_GUARD_COOLDOWN_MAX_MS: 15000,
  SCROLL_GUARD_ALLOWED_STEP_PX: 110,
  SCROLL_GUARD_ALLOWED_STEP_MIN_INTERVAL_MS: 120,
  SCROLL_GUARD_MIN_VIEWED_DENSITY: 0.55,
  SCROLL_GUARD_DENSITY_WINDOW_MS: 6000
})

export const DOM_IDS: IDomIdentifiers = Object.freeze({
  STORAGE_KEY: 'lhvj-show-hidden',
  SCROLL_GUARD_STORAGE_KEY: 'lhvj-scroll-guard-enabled',
  DETECTION_MODE_STORAGE_KEY: 'lhvj-detection-mode',
  RELOAD_ON_NAVIGATION_STORAGE_KEY: 'lhvj-reload-on-navigation',
  VIEWED_HIGHLIGHT_COLOR_STORAGE_KEY: 'lhvj-viewed-highlight-color',
  APPLIED_HIGHLIGHT_COLOR_STORAGE_KEY: 'lhvj-applied-highlight-color',
  ACTIVE_HIGHLIGHT_COLOR_STORAGE_KEY: 'lhvj-active-highlight-color',
  KEYWORD_HIGHLIGHT_COLOR_STORAGE_KEY: 'lhvj-keyword-highlight-color',
  CUSTOM_KEYWORDS_STORAGE_KEY: 'lhvj-custom-keywords',
  HIGHLIGHT_OPACITY_STORAGE_KEY: 'lhvj-highlight-opacity',
  UI_POSITION_KEY: 'lhvj-ui-position',
  POPUP_BOUNDS_STORAGE_KEY: 'lhvj-popup-bounds',
  UPDATE_CHECK_STORAGE_KEY: 'lhvj-update-check',
  HIDDEN_CLASS: 'lhvj-hidden-by-script',
  UI_ID: 'lhvj-toggle-root',
  VIEWED_HIGHLIGHT_CLASS: 'lhvj-viewed-highlight',
  APPLIED_HIGHLIGHT_CLASS: 'lhvj-applied-highlight',
  ACTIVE_HIGHLIGHT_CLASS: 'lhvj-active-highlight',
  KEYWORD_HIGHLIGHT_CLASS: 'lhvj-keyword-highlight'
})

export const STORAGE_KEYS = {
  SHOW_HIDDEN: DOM_IDS.STORAGE_KEY,
  SCROLL_GUARD: DOM_IDS.SCROLL_GUARD_STORAGE_KEY,
  DETECTION_MODE: DOM_IDS.DETECTION_MODE_STORAGE_KEY,
  RELOAD_NAVIGATION: DOM_IDS.RELOAD_ON_NAVIGATION_STORAGE_KEY,
  VIEWED_COLOR: DOM_IDS.VIEWED_HIGHLIGHT_COLOR_STORAGE_KEY,
  APPLIED_COLOR: DOM_IDS.APPLIED_HIGHLIGHT_COLOR_STORAGE_KEY,
  ACTIVE_COLOR: DOM_IDS.ACTIVE_HIGHLIGHT_COLOR_STORAGE_KEY,
  KEYWORD_COLOR: DOM_IDS.KEYWORD_HIGHLIGHT_COLOR_STORAGE_KEY,
  CUSTOM_KEYWORDS: DOM_IDS.CUSTOM_KEYWORDS_STORAGE_KEY,
  OPACITY: DOM_IDS.HIGHLIGHT_OPACITY_STORAGE_KEY
} as const

export const DEFAULTS: Record<string, string> = {
  [STORAGE_KEYS.VIEWED_COLOR]: '#2ecc71',
  [STORAGE_KEYS.APPLIED_COLOR]: '#f59e0b',
  [STORAGE_KEYS.ACTIVE_COLOR]: '#0a66c2',
  [STORAGE_KEYS.KEYWORD_COLOR]: '#9b59b6',
  [STORAGE_KEYS.OPACITY]: '0.10'
} as const
